apiVersion: v1
kind: Service
metadata:
  name: node-docker-demo-service
spec:
  #type: NodePort
  selector:
    app: node-docker-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
     # nodePort: 30001  # You can access this via Minikube at this port
  type: NodePort
