apiVersion: v1
kind: Service
metadata:
  name: node-docker-demo-service
spec:
  type: NodePort
  selector:
    app: node-docker-demo
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 3000  # You can access this via Minikube at this port
